# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Everything above this line is generated by deploy_cell: https://github.com/path-robotics/deploy_cell/blob/a6b6f9c377a935abe194a6fae6c708dc260a9cea/roles/bootstrap_install/templates/profile.j2
# Everything below is my personal stuff
#
# Load up https://github.com/pyenv/pyenv
if command -v pyenv 2>&1 >/dev/null; then
	export PYENV_ROOT="$HOME/.pyenv"
	export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init -)"
fi

# Load up https://github.com/nodenv/nodenv
if command -v nodenv 2>&1 >/dev/null; then
	eval "$(nodenv init -)"
	# Do I need this?
	NODE_PATH="/usr/local/lib/node_modules"
fi

# Load up https://github.com/rbenv/rbenv
if command -v rbenv 2>&1 >/dev/null; then
	eval "$(rbenv init -)"
fi

# https://github.com/junegunn/fzf
if command -v fzf 2>&1 >/dev/null; then
	eval "$(fzf --bash)"
fi

source ~/.forge-aliases.bash
. "$HOME/.cargo/env"
