tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash-git-prompt"
brew "docker", link: false
brew "docker-compose", link: false
brew "gnupg"
brew "graphviz"
brew "neovim"
brew "nodenv"
brew "postgresql"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rust"
brew "tmux"
brew "heroku/brew/heroku"
cask "alfred"
cask "brave"
cask "caprine"
cask "dash"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spotify"
