# split windows like vim
# vim's definition of a horizontal/vertical split is reversed from tmux's
bind s split-window -v
bind v split-window -h

bind ^s split-window -v
bind ^v split-window -h

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt

# allow rodent use
bind m set -g mouse on \; display 'Mouse: ON'
bind M set -g mouse off \; display 'Mouse: OFF'

# vi-style controls for copy mode
setw -g mode-keys vi
#
# # Set the prefix to ^A, like screen
unbind C-b
set -g prefix ^A
bind a send-prefix

bind K confirm kill-server
bind X confirm kill-window

# longer scrollback
set -g history-limit 10000

# active terminal darkblue border, non-active white
set -g pane-border-style fg=colour247,bg=default
set -g pane-active-border-style fg=red,bg=default

# set a 256color $TERM variable so programs inside tmux know they can use 256 colors
set -g default-terminal screen-256color

# # reload tmux config file with C-a r
bind-key r source-file ~/.tmux.conf \; display-message '~/.tmux.conf reloaded'

# open splits and windows in same pwd
bind s split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# neovim in tmux causes delay when pressing ESC, this reduces it
set -g escape-time 0 # ms

# # left side of status bar holds "(>- session name -<)"
set -g status-left-length 100
set -g status-left ''

# right side of status bar holds "[host name] (date time)"
set -g status-right-length 100
set -g status-right '#[fg=yellow] #H#[fg=white]:#[fg=yellow]#S #[fg=blue,bg=default] %m/%d/%Y %-l:%M %p'

# make foreground window look like bold yellow foreground tab
set-window-option -g window-status-current-format '#[fg=black,bg=yellow] #I #[fg=white,bg=brightblack] #W #[default]'

set-option -g renumber-windows on

# Copy-paste integration
set-option -g default-command "bash"

# Use system clipboard via xclip
set-option -g set-clipboard on

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe "cat"

# Setup mouse to copy selection on drag
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "cat"

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "cat"

# Bind ']' to use pbpaste
bind ] run "tmux set-buffer \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"
