require("plugins")

require("auto-commands")
require("colors")
require("folding")
require("keymaps")
require("lsp")
require("options")

require("plugins.fzf")
require("plugins.neoterm")
require("plugins.nerdtree")
require("plugins.tagbar")
require("plugins.treesitter")
require("plugins.vim-test")
require("plugins.word-motion")
